-- Run in Supabase SQL Editor
ALTER TABLE beats ADD COLUMN IF NOT EXISTS buyer_name TEXT DEFAULT '';
ALTER TABLE beats ADD COLUMN IF NOT EXISTS buyer_email TEXT DEFAULT '';
ALTER TABLE beats ADD COLUMN IF NOT EXISTS sold_at TIMESTAMPTZ;
ALTER TABLE beats ADD COLUMN IF NOT EXISTS order_number TEXT DEFAULT '';
